import { UserIdentity } from "@/plugins/RTC/types";

export enum IncomingMessageTypes {
  CONNECTION_SUCCESS = "CONNECTED",
  ROOM_MEMBER_GOT_REMOVED = "OTHER_GOT_REMOVED",
  ME_GOT_REMOVED = "SELF_GOT_REMOVED",
  ROOM_CREATED = "CREATED_ROOM",
  ROOM_JOIN_ERROR = "ROOM_JOIN_ERROR",
  ROOM_CREATE_ERROR = "ROOM_CREATE_ERROR",
  JOIN_REQ = "JOIN_ROOM_REQ",
  ROOM_JOINED = "JOINED_ROOM",
  NEW_ROOM_MEMBER = "NEW_MEMBER",
  ROOM_MEMBER_LEFT = "MEMBER_LEFT",
  ROOM_DESTROYED = "DESTROYED_ROOM",
  RTC_EVENT = "0",
}

export enum OutgoingMessageTypes {
  CREATE_ROOM = "CREATE_ROOM",
  JOIN_ROOM_REQ = "JOIN_ROOM",
  REMOVE_MEMBER = "REMOVE_MEMBER",
  ACCEPT_JOIN_ROOM_REQ = "ACCEPT_JOIN_ROOM_REQ",
  ME_DISCONNECTED = "USER_DISCONNECTED",
  RTC_EVENT = "0",
}

export interface WebSocketUser extends UserIdentity {
  socketId: string;
}
